name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm init -y
          npm install sass

      - name: Create dist directory
        run: mkdir -p dist/css

      - name: Compile SCSS to CSS
        run: |
          npx sass --style=compressed --no-source-map assets/sass/:dist/css/
          echo "Compiled CSS files:"
          ls -la dist/css/
          echo "Content of style.css:"
          cat dist/css/style.css

      - name: Debug SASS files
        run: |
          echo "SASS files in assets/sass/:"
          ls -la assets/sass/
          echo "Current directory structure:"
          tree || true

      - name: Prepare GitHub Pages deployment
        run: |
          touch .nojekyll
          cp -r dist/css/* dist/
          echo "Final dist directory contents:"
          ls -la dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
